#-----------------------------------------------------------------------------#
# This file defines all the paramters of the problem
# It basically:
#   ......
#  The property shapeID should have one of the following values:  0 or 1 or 2
#  each values index to a different object            
#-----------------------------------------------------------------------------#


object:
    shape:
      shapeID: 0  # 1 , 2
      circle:  #(0)
        radius: 0.265
        inertia: 0.0351125 #1/2 * r**2;
      rectangle: #(1)
        height: 0.5
        width: 0.5
        inertia: 0.04167 # (2*r)^2 / 6;
      parallelogram: #(2)
        height: 0.36
        width: 0.64
        inertia: 0.04493 # (1/12) * (h^2 + w^2);
    friction: 0.5
    mass: 1

gravity: [0, -9.81, 0]

constraints:
    maxDistatSwing: -1
other:
